import { execFile, spawn } from "node:child_process";
import { AIReviewComment, AIReviewResult } from "./ai";
import { ImpactAnalysisReport } from "./analyzer/impact";
import { GitCommitInfo } from "./workspace";

export interface OpenCodeReviewOptions {
  repoPath: string;
  title: string;
  author: string;
  repoName: string;
  targetBranch: string;
  description?: string | undefined;
  commits?: GitCommitInfo[] | undefined;
  rawDiff?: string | undefined;
  impactReport?: ImpactAnalysisReport | undefined;
  timeoutMs?: number | undefined;
}

export class OpenCodeRunner {
  private opencodeBin: string;

  constructor(binPath?: string) {
    this.opencodeBin = binPath || process.env.OPENCODE_BIN || "opencode";
  }

  public buildReviewPrompt(options: {
    title: string;
    author: string;
    repoName: string;
    targetBranch: string;
    description?: string | undefined;
    commits?: GitCommitInfo[] | undefined;
    rawDiff?: string | undefined;
    impactSummary?: string | undefined;
  }): string {
    const commitsText =
      options.commits && options.commits.length > 0
        ? options.commits
            .map((c) => `- [${c.hash}] ${c.message} (${c.author})`)
            .join("\n")
        : "Không có commit log";

    return `
Bạn là AI Senior Code Reviewer. Bạn đang ở trong repository '${options.repoName}'.
NHIỆM VỤ CỦA BẠN: Phân tích và review các thay đổi trong Merge Request dưới đây.

QUY TẮC QUAN TRỌNG:
- NGÔN NGỮ: BẮT BUỘC trả về nội dung review (tóm tắt summary, mô tả lỗi trong text, giải thích gợi ý trong suggestion) 100% BẰNG TIẾNG VIỆT. Tuyệt đối không dùng tiếng Anh cho nội dung nhận xét.
- PHẠM VI (SCOPE): CHỈ tập trung vào các file và đoạn code được thay đổi trong DIFF và các caller liên quan trực tiếp. KHÔNG quét lan man toàn bộ cấu trúc dự án.
- ĐỊNH DẠNG: BẮT BUỘC TRẢ VỀ DUY NHẤT 1 KHỐI JSON THEO SCHEMA. KHÔNG in ra lời dẫn, suy nghĩ (thinking), hay văn bản tự do.

THÔNG TIN MERGE REQUEST:
- Tiêu đề: ${options.title}
- Tác giả: ${options.author}
- Nhánh đích (Target Branch): ${options.targetBranch}
${options.description ? `- Mô tả: ${options.description}` : ""}

DANH SÁCH COMMITS MỚI:
${commitsText}

${options.impactSummary ? `GHI CHÚ VỀ PHẠM VI ẢNH HƯỞNG (CALLERS SCAN):\n${options.impactSummary}\n` : ""}

DIFF CỦA CÁC THAY ĐỔI:
${options.rawDiff || "(Xem git diff trực tiếp trong repository)"}

TIÊU CHÍ REVIEW:
1. 🚨 Bug & Logic: Null/undefined pointer, race conditions, edge-cases.
2. 🔒 Bảo mật: Injection, leak secrets/tokens, thiếu validation.
3. ⚡ Hiệu năng: N+1 query, blocking calls, rò rỉ bộ nhớ.
4. 💥 Breaking changes: Phá vỡ signature các hàm/class đang được gọi.

ĐỊNH DẠNG ĐẦU RA BẮT BUỘC (DUY NHẤT 1 KHỐI JSON THEO SCHEMA):
\`\`\`json
{
  "summary": "Tóm tắt (2-3 câu) HOÀN TOÀN bằng Tiếng Việt về chất lượng MR và điểm cần chú ý",
  "verdict": "APPROVE" | "REQUEST_CHANGES" | "COMMENT",
  "riskLevel": "LOW" | "MEDIUM" | "HIGH",
  "comments": [
    {
      "path": "đường_dẫn_file",
      "line": 42,
      "severity": "CRITICAL" | "WARNING" | "SUGGESTION",
      "category": "SECURITY" | "BUG" | "PERFORMANCE" | "CLEAN_CODE",
      "text": "Mô tả vấn đề và rủi ro HOÀN TOÀN bằng Tiếng Việt",
      "suggestion": "Code gợi ý sửa đổi (kèm giải thích bằng Tiếng Việt nếu cần)"
    }
  ]
}
\`\`\`
`.trim();
  }

  public parseOpenCodeOutput(rawOutput: string): AIReviewResult {
    // 1. Strip ANSI escape sequences generated by terminal CLI / spinners
    let clean = rawOutput
      .replace(/\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])/g, "")
      .trim();

    // 2. Extract from markdown codeblock if present
    if (clean.includes("```json")) {
      const match = clean.match(/```json\s*([\s\S]*?)\s*```/);
      if (match && match[1]) {
        clean = match[1].trim();
      }
    } else if (clean.includes("```")) {
      const match = clean.match(/```\s*([\s\S]*?)\s*```/);
      if (match && match[1]) {
        clean = match[1].trim();
      }
    }

    // 3. Find outermost JSON object
    const firstBrace = clean.indexOf("{");
    const lastBrace = clean.lastIndexOf("}");
    if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
      clean = clean.substring(firstBrace, lastBrace + 1);
    }

    try {
      const parsed = JSON.parse(clean);
      const comments: AIReviewComment[] = Array.isArray(parsed.comments)
        ? parsed.comments.map((c: any) => ({
            path: String(c.path || ""),
            line: Number(c.line) || 1,
            severity: (["CRITICAL", "WARNING", "SUGGESTION"].includes(
              c.severity,
            )
              ? c.severity
              : "WARNING") as any,
            category: ([
              "SECURITY",
              "PERFORMANCE",
              "CLEAN_CODE",
              "BUG",
            ].includes(c.category)
              ? c.category
              : "BUG") as any,
            text: String(c.text || ""),
            suggestion: c.suggestion ? String(c.suggestion) : undefined,
          }))
        : [];

      return {
        summary:
          parsed.summary ||
          "OpenCode đã hoàn thành phân tích repository và Merge Request.",
        verdict:
          parsed.verdict || (comments.length > 0 ? "COMMENT" : "APPROVE"),
        riskLevel: parsed.riskLevel || (comments.length > 0 ? "MEDIUM" : "LOW"),
        comments,
      };
    } catch (err) {
      console.warn(
        `[OpenCodeRunner] Failed to parse JSON from output: ${err}\n[OpenCodeRunner] Raw output preview:\n${rawOutput.slice(0, 400)}`,
      );

      // Heuristic fallback: Try to infer verdict & summary from plain text
      const isApprove =
        clean.toLowerCase().includes("approve") &&
        !clean.toLowerCase().includes("request_changes");
      const isRequestChanges =
        clean.toLowerCase().includes("request_changes") ||
        clean.toLowerCase().includes("request changes");

      const verdict = isRequestChanges
        ? "REQUEST_CHANGES"
        : isApprove
          ? "APPROVE"
          : "COMMENT";

      return {
        summary:
          clean.slice(0, 500) ||
          "OpenCode đã hoàn thành phân tích repository và Merge Request.",
        verdict,
        riskLevel: verdict === "REQUEST_CHANGES" ? "HIGH" : "LOW",
        comments: [],
      };
    }
  }

  /**
   * Khởi chạy OpenCode CLI trên VPS trong thư mục repo, thu thập kết quả và tự động tắt process
   */
  public async runReview(
    options: OpenCodeReviewOptions,
  ): Promise<AIReviewResult> {
    const prompt = this.buildReviewPrompt({
      title: options.title,
      author: options.author,
      repoName: options.repoName,
      targetBranch: options.targetBranch,
      description: options.description,
      commits: options.commits,
      rawDiff: options.rawDiff,
      impactSummary: options.impactReport?.summary,
    });

    const timeoutMs =
      options.timeoutMs ||
      Number(process.env.OPENCODE_TIMEOUT_MS) ||
      15 * 60 * 1000;

    console.log(
      `[OpenCodeRunner] Starting OpenCode CLI in ${options.repoPath}...`,
    );

    return new Promise<AIReviewResult>((resolve, reject) => {
      let stdoutData = "";
      let stderrData = "";
      let isFinished = false;

      // Prepare CLI arguments
      const args = ["run", prompt];
      let model = (process.env.OPENCODE_MODEL || "opencode/big-pickle").trim();
      if (
        model.toLowerCase() === "big pickle" ||
        model.toLowerCase() === "big-pickle"
      ) {
        model = "opencode/big-pickle";
      }
      if (model) {
        args.push("-m", model);
      }

      console.log(
        `[OpenCodeRunner] Starting OpenCode CLI (model: '${model}') in ${options.repoPath}...`,
      );

      // Spawn opencode process in non-interactive batch mode
      const child = spawn(this.opencodeBin, args, {
        cwd: options.repoPath,
        env: {
          ...process.env,
          CI: "true",
          NO_COLOR: "1",
        },
        stdio: ["ignore", "pipe", "pipe"],
      });

      const timer = setTimeout(() => {
        if (!isFinished) {
          isFinished = true;
          console.warn(
            `[OpenCodeRunner] Process timed out after ${timeoutMs}ms, killing...`,
          );
          child.kill("SIGKILL");
          reject(
            new Error(`OpenCode execution timed out after ${timeoutMs}ms`),
          );
        }
      }, timeoutMs);

      child.stdout.on("data", (chunk) => {
        const str = chunk.toString();
        stdoutData += str;
      });

      child.stderr.on("data", (chunk) => {
        const str = chunk.toString();
        stderrData += str;
      });

      child.on("error", (err) => {
        if (!isFinished) {
          isFinished = true;
          clearTimeout(timer);
          console.error("[OpenCodeRunner] Spawn error:", err);
          reject(err);
        }
      });

      child.on("close", (code) => {
        if (isFinished) return;
        isFinished = true;
        clearTimeout(timer);

        console.log(
          `[OpenCodeRunner] OpenCode process exited with code ${code}. Session closed.`,
        );

        if (code !== 0 && !stdoutData.trim()) {
          reject(
            new Error(
              `OpenCode failed with code ${code}: ${stderrData.slice(0, 300)}`,
            ),
          );
          return;
        }

        const reviewResult = this.parseOpenCodeOutput(stdoutData);
        resolve(reviewResult);
      });
    });
  }
}
